enum EventType {
  SEND_MESSAGE = "SEND_MESSAGE",
  CREATE_ROOM = "CREATE_ROOM",
  JOIN_ROOM = "JOIN_ROOM",
  UNJOIN_ROOM = "UNJOIN_ROOM",
  ENTER_ROOM = "ENTER_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  LIST_JOINABLE_ROOMS = "LIST_JOINABLE_ROOMS",
  LIST_ROOMS = "LIST_ROOMS",
  LIST_ROOM_MEMBERS = "LIST_ROOM_MEMBERS",
  LIST_DIRECT_CONVERSATIONS = "LIST_DIRECT_CONVERSATIONS",
  LIST_DIRECT_MESSAGES = "LIST_DIRECT_MESSAGES",
  LIST_INVITABLE_USERS = "LIST_INVITABLE_USERS",
  MEMBER_ENTERED_ROOM = "MEMBER_ENTERED_ROOM",
  MEMBER_LEFT_ROOM = "MEMBER_LEFT_ROOM",
  CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED",
  CONNECTION_CLOSED = "CONNECTION_CLOSED",
}

export default EventType;
