enum EventType {
  SEND_MESSAGE = "SEND_MESSAGE",
  ERROR = "ERROR",
  CREATE_ROOM = "CREATE_ROOM",
  JOIN_ROOM = "JOIN_ROOM",
  UNJOIN_ROOM = "UNJOIN_ROOM",
  ENTER_ROOM = "ENTER_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  JOINABLE_ROOMS = "JOINABLE_ROOMS",
  LIST_ROOMS = "LIST_ROOMS",
  LIST_ROOM_MEMBERS = "LIST_ROOM_MEMBERS",
  MEMBER_ENTERED_ROOM = "MEMBER_ENTERED_ROOM",
  MEMBER_LEFT_ROOM = "MEMBER_LEFT_ROOM",
  DIRECT_CONVERSATIONS = "DIRECT_CONVERSATIONS",
  CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED",
  CONNECTION_CLOSED = "CONNECTION_CLOSED",
}

export default EventType;
