name: CI Workflow

on:
  push:
    branches:
      - main  # Adjust this to your desired branch
  pull_request:
    branches:
      - main  # Adjust this to your desired branch

jobs:
  test:
    runs-on: ubuntu-latest

    environment:
      name: tests

    env:
      JWT_SIGNATURE: ${{ secrets.JWT_SIGNATURE }}
      EXPRESS_PORT: ${{ secrets.EXPRESS_PORT }}
      WSS_URL: ${{ secrets.WSS_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.3.0'

    - name: Install dependencies
      run: npm install

    - name: Run Jest Tests
      run: npm run test:jest

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v4
      with:
        start: npm start
        wait-on: 'http://localhost:3000'  # Adjust to the port your app runs on
        wait-on-timeout: 60 # Wait time for the app to be fully available