name: CI Workflow
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]
jobs:
  test:
    runs-on: ubuntu-latest
    # All pull request are automatically tested, so we can safely (I hope) skip testing again after merge..
    # Therefore, only run tests on main if it isn't a merged PR.
    if: ${{ github.event.pull_request.merged == 'false' }}
    environment:
      name: tests
    env:
      JWT_SIGNATURE: ${{ secrets.JWT_SIGNATURE }}
      EXPRESS_PORT: ${{ secrets.EXPRESS_PORT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      DATABASE_PROVIDER: ${{ secrets.DATABASE_PROVIDER }}
    steps:
    - name: Check if PR is merged
      if: ${{ github.event.pull_request.merged == 'false' }}
      run: echo "This pull request is not merged, running job."
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.3.0'
    - name: Install dependencies
      run: npm install
    - name: Run Jest Tests
      run: npm run test:jest
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v4
      with:
        start: npm start
        wait-on: 'http://localhost:3000'  # Adjust to the port your app runs on
        wait-on-timeout: 60 # Wait time for the app to be fully available
        record: false # record results to cypress cloud